o_auth_sign_in:
  path: /oauthsignin/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\OAuthSignIn\Controllers\OAuthSignInConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: Configuration
    _legacy_link: Social login