services:
  _defaults:
    public: true

  # FirstModule configuration text form
  prestashop.module.firstmodule.form.type.firstmodule_configuration_text:
    class: 'PrestaShop\Module\FirstModule\Form\FirstModuleFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.firstmodule.form.firstmodule_data_configuration:
    class: 'PrestaShop\Module\FirstModule\Form\FirstModuleDataConfiguration'
    arguments: ['@prestashop.adapter.legacy.configuration']

  prestashop.module.firstmodule.form.firstmodule_form_data_provider:
    class: 'PrestaShop\Module\FirstModule\Form\FirstModuleFormDataProvider'
    arguments:
      - '@prestashop.module.firstmodule.form.firstmodule_data_configuration'

  prestashop.module.firstmodule.form.firstmodule_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.firstmodule.form.firstmodule_form_data_provider'
      - 'PrestaShop\Module\FirstModule\Form\FirstModuleFormType'
      - 'FirstModuleConfiguration'

