services:
  _defaults:
    public: true

  # OAuthSignIn configuration text form
  prestashop.module.oauthsignin.form.type.oauthsignin_configuration_text:
    class: 'PrestaShop\Module\OAuthSignIn\Form\OAuthSignInFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.oauthsignin.form.oauthsignin_data_configuration:
    class: 'PrestaShop\Module\OAuthSignIn\Form\OAuthSignInDataConfiguration'
    arguments: 
      - '@prestashop.adapter.legacy.configuration'
      - '@router'

  prestashop.module.oauthsignin.form.oauthsignin_form_data_provider:
    class: 'PrestaShop\Module\OAuthSignIn\Form\OAuthSignInFormDataProvider'
    arguments:
      - '@prestashop.module.oauthsignin.form.oauthsignin_data_configuration'

  prestashop.module.oauthsignin.form.oauthsignin_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.oauthsignin.form.oauthsignin_form_data_provider'
      - 'PrestaShop\Module\OAuthSignIn\Form\OAuthSignInFormType'
      - 'OAuthSignInConfiguration'

  prestashop.module.oauthsignin.google_login_service:
    class: 'PrestaShop\Module\OAuthSignIn\Services\GoogleLoginService'